# Generated by Django 4.0.6 on 2022-08-07 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('open', 'open'), ('close', 'close')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'low'), ('high', 'high'), ('medium', 'medium')], default='low', max_length=20)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('assignedTo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
